imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    maith_newsletter_handler.class: AppBundle\Service\LocalNewsletterHandler
framework:
    #esi:             ~
    translator:
      fallbacks: ["%locale%"]
      logging:  true
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: v1
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: bunniesKinder2
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - LexikFormFilterBundle:Form:form_div_layout.html.twig

# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ ]
    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # Other connections parameters
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: AppBundle\Entity\Progenitor
    registration:
        confirmation:
            enabled:    true

#Stof doctrine extension
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: false # not needed: listeners are not enabled by default
            timestampable: true
            sortable: true
            sluggable: false
            translatable: false

jms_security_extra:
    # Enables expression language
    expressions: true

lexik_form_filter:
    where_method: ~  # null | and | or

services:
    fos_user.doctrine_registry:
        alias: doctrine

#Captcha
gregwar_captcha: ~