security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
