app_estudiante:
    resource: "@AppBundle/Resources/config/routing/estudiante.yml"
    prefix:   /estudiante

app:
    resource: "@AppBundle/Resources/config/routing/cuentas.yml"
    prefix:   /admin

admin_index:
    path:     /admin/
    defaults: { _controller: AppBundle:Cuentas:index }
    
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }  