app_admin_costos:
    resource: "@AppBundle/Resources/config/routing/costos.yml"
    prefix:   /admin/costos

app_admin_descuento:
    resource: "@AppBundle/Resources/config/routing/descuento.yml"
    prefix:   /admin/descuento

app_admin_actividades:
    resource: "@AppBundle/Resources/config/routing/actividad.yml"
    prefix:   /admin/actividades

app_admin_progenitor:
    resource: "@AppBundle/Resources/config/routing/progenitor.yml"
    prefix:   /admin/progenitor

app_estudiante:
    resource: "@AppBundle/Resources/config/routing/estudiante.yml"
    prefix:   /admin/estudiante

cuentas:
    resource: "@AppBundle/Resources/config/routing/cuentas.yml"
    prefix:   /admin/cuentas

cobros:
    resource: "@AppBundle/Resources/config/routing/cobros.yml"
    prefix:   /admin/cobros

estudiante_progenitor:
    resource: "@AppBundle/Resources/config/routing/estudianteprogenitor.yml"
    prefix:   /admin/estudiante-progenitor

admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:   /

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
activities:    
    path:     /actividades.html
    defaults: { _controller: AppBundle:Default:activities }
    
contacto:    
    path:     /contacto.html
    defaults: { _controller: AppBundle:Default:contact }
    
inscripciones:    
    path:     /inscripciones.html
    defaults: { _controller: AppBundle:Default:inscripciones }
    
migrations:
    resource: "@AppBundle/Resources/config/routing/migrations.yml"
    prefix:   /migrations


