# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    kinder_cobro_service.class: AppBundle\Service\CobroService
    kinder_estudiantes_service.class: AppBundle\Service\EstudiantesService
    kinder_progenitores_service.class: AppBundle\Service\ProgenitoresService

services:
    facturas:
        class: AppBundle\Service\FacturasManager
        arguments: ["@doctrine.orm.entity_manager", "@logger"]

    cuentas:
        class: AppBundle\Service\CuentasService
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
    newslettersync:
        class: AppBundle\Service\NewsletterSyncService
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
        lazy: true

    migrations:
        class: AppBundle\Service\MigrationService
        arguments: ["@doctrine.orm.entity_manager", "@logger", "%old_db_host%", "%old_db_user%", "%old_db_password%", '@cuentas', '@newslettersync', '@fos_user.user_manager', '@facturas']
        lazy: true
    pdfs:
        class: AppBundle\Service\PdfManager
        arguments: ["@doctrine.orm.entity_manager", "@logger", "%kernel.root_dir%"]
        lazy: true

    kinder.cobro:
        class: %kinder_cobro_service.class%
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
        lazy: true

    kinder.estudiantes:
        class: %kinder_estudiantes_service.class%
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
        lazy: true

    kinder.progenitores:
        class: %kinder_progenitores_service.class%
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
        lazy: true
