ALTER TABLE actividades DROP FOREIGN KEY actividades_md_news_letter_group_id_md_news_letter_group_id;
ALTER TABLE cobro DROP FOREIGN KEY cobro_cuenta_id_cuenta_id;
ALTER TABLE cuentapadre DROP FOREIGN KEY cuentapadre_cuenta_id_cuenta_id;
ALTER TABLE cuentapadre DROP FOREIGN KEY cuentapadre_progenitor_id_progenitor_id;
ALTER TABLE cuentausuario DROP FOREIGN KEY cuentausuario_cuenta_id_cuenta_id;
ALTER TABLE cuentausuario DROP FOREIGN KEY cuentausuario_usuario_id_usuario_id;
ALTER TABLE exoneracion DROP FOREIGN KEY exoneracion_usuario_id_usuario_id;
ALTER TABLE facturaFinal DROP FOREIGN KEY facturaFinal_cuenta_id_cuenta_id;
ALTER TABLE facturaFinalDetalle DROP FOREIGN KEY facturaFinalDetalle_factura_id_facturaFinal_id;
ALTER TABLE facturaUsuario DROP FOREIGN KEY facturaUsuario_usuario_id_usuario_id;
ALTER TABLE facturaUsuarioDetalle DROP FOREIGN KEY facturaUsuarioDetalle_factura_id_facturaUsuario_id;
ALTER TABLE facturausuariofinal DROP FOREIGN KEY facturausuariofinal_factura_final_id_facturaFinal_id;
ALTER TABLE facturausuariofinal DROP FOREIGN KEY facturausuariofinal_factura_usuario_id_facturaUsuario_id;
ALTER TABLE hermanos DROP FOREIGN KEY hermanos_usuario_from_usuario_id;
ALTER TABLE hermanos DROP FOREIGN KEY hermanos_usuario_to_usuario_id;
ALTER TABLE md_content DROP FOREIGN KEY md_content_md_user_id_md_user_id;
ALTER TABLE md_content_relation DROP FOREIGN KEY md_content_relation_md_content_id_first_md_content_id;
ALTER TABLE md_content_relation DROP FOREIGN KEY md_content_relation_md_content_id_second_md_content_id;
ALTER TABLE md_galeria_translation DROP FOREIGN KEY md_galeria_translation_id_md_galeria_id;
ALTER TABLE md_media_album DROP FOREIGN KEY md_media_album_md_media_content_id_md_media_content_id;
ALTER TABLE md_media_album DROP FOREIGN KEY md_media_album_md_media_id_md_media_id;
ALTER TABLE md_media_album_content DROP FOREIGN KEY md_media_album_content_md_media_album_id_md_media_album_id;
ALTER TABLE md_media_album_content DROP FOREIGN KEY md_media_album_content_md_media_content_id_md_media_content_id;
ALTER TABLE md_news_letter_group_sended DROP FOREIGN KEY mmmi;
ALTER TABLE md_news_letter_group_sended DROP FOREIGN KEY mmmi_1;
ALTER TABLE md_news_letter_group_user DROP FOREIGN KEY mmmi_2;
ALTER TABLE md_news_letter_group_user DROP FOREIGN KEY mmmi_3;
ALTER TABLE md_news_letter_user DROP FOREIGN KEY md_news_letter_user_md_user_id_md_user_id;
ALTER TABLE md_newsletter_content_sended DROP FOREIGN KEY mmmi_4;
ALTER TABLE md_newsletter_send DROP FOREIGN KEY md_newsletter_send_md_news_letter_user_id_md_news_letter_user_id;
ALTER TABLE md_newsletter_send DROP FOREIGN KEY mmmi_5;
ALTER TABLE md_passport DROP FOREIGN KEY md_passport_md_user_id_md_user_id;
ALTER TABLE md_passport_remember_key DROP FOREIGN KEY md_passport_remember_key_md_passport_id_md_passport_id;
ALTER TABLE md_user_search DROP FOREIGN KEY md_user_search_md_user_id_md_user_id;
ALTER TABLE pagos DROP FOREIGN KEY pagos_usuario_id_usuario_id;
ALTER TABLE progenitor DROP FOREIGN KEY progenitor_md_user_id_md_user_id;
ALTER TABLE usuario DROP FOREIGN KEY usuario_billetera_id_billetera_id;
ALTER TABLE usuario_actividades DROP FOREIGN KEY usuario_actividades_actividad_id_actividades_id;
ALTER TABLE usuario_actividades DROP FOREIGN KEY usuario_actividades_usuario_id_usuario_id;
ALTER TABLE usuario_progenitor DROP FOREIGN KEY usuario_progenitor_progenitor_id_progenitor_id;
ALTER TABLE usuario_progenitor DROP FOREIGN KEY usuario_progenitor_usuario_id_usuario_id;


ALTER TABLE actividades DROP INDEX md_news_letter_group_id_idx, ADD UNIQUE INDEX UNIQ_73D548DE8E4E854F (md_news_letter_group_id);
ALTER TABLE md_user CHANGE super_admin super_admin TINYINT(1) NOT NULL;
ALTER TABLE facturaFinalDetalle DROP FOREIGN KEY facturaFinalDetalle_factura_id_facturaFinal_id;
ALTER TABLE facturaFinalDetalle CHANGE factura_id factura_id BIGINT DEFAULT NULL, CHANGE amount amount DOUBLE PRECISION NOT NULL;
ALTER TABLE facturaFinalDetalle ADD CONSTRAINT FK_C70BF15EF04F795F FOREIGN KEY (factura_id) REFERENCES facturaFinal (id);
ALTER TABLE md_user_profile CHANGE country_code country_code VARCHAR(2) DEFAULT NULL;
ALTER TABLE progenitor DROP FOREIGN KEY progenitor_md_user_id_md_user_id;
--ALTER TABLE cuentapadre DROP PRIMARY KEY;
ALTER TABLE cuentapadre CHANGE cuenta_id cuenta_id INT NOT NULL, CHANGE progenitor_id progenitor_id INT NOT NULL;
--ALTER TABLE cuentapadre ADD PRIMARY KEY (progenitor_id, cuenta_id);
ALTER TABLE usuario_progenitor DROP FOREIGN KEY usuario_progenitor_progenitor_id_progenitor_id;
ALTER TABLE usuario_progenitor DROP FOREIGN KEY usuario_progenitor_usuario_id_usuario_id;
ALTER TABLE usuario_progenitor DROP PRIMARY KEY;
ALTER TABLE usuario_progenitor CHANGE usuario_id usuario_id INT NOT NULL, CHANGE progenitor_id progenitor_id INT NOT NULL;
ALTER TABLE usuario_progenitor ADD CONSTRAINT FK_48FFC4DB93BAFCB0 FOREIGN KEY (progenitor_id) REFERENCES progenitor (id);
ALTER TABLE usuario_progenitor ADD CONSTRAINT FK_48FFC4DBDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id);
ALTER TABLE usuario_progenitor ADD PRIMARY KEY (progenitor_id, usuario_id);
ALTER TABLE md_passport_remember_key DROP FOREIGN KEY md_passport_remember_key_md_passport_id_md_passport_id;
ALTER TABLE md_passport_remember_key CHANGE id id INT NOT NULL, CHANGE ip_address ip_address VARCHAR(50) NOT NULL;
ALTER TABLE md_media_album_content DROP FOREIGN KEY md_media_album_content_md_media_album_id_md_media_album_id;
ALTER TABLE md_media_album_content DROP FOREIGN KEY md_media_album_content_md_media_content_id_md_media_content_id;
--DROP INDEX IDX_553E5CD150381FB4 ON md_media_album_content;
ALTER TABLE md_media_album_content CHANGE md_media_album_id md_media_album_id INT NOT NULL, CHANGE md_media_content_id md_media_content_id INT NOT NULL;
ALTER TABLE md_passport DROP FOREIGN KEY md_passport_md_user_id_md_user_id;
ALTER TABLE md_passport CHANGE account_active account_active TINYINT(1) NOT NULL, CHANGE account_blocked account_blocked TINYINT(1) NOT NULL;
ALTER TABLE md_news_letter_group_user DROP FOREIGN KEY mmmi_2;
ALTER TABLE md_news_letter_group_user DROP FOREIGN KEY mmmi_3;
--DROP INDEX IDX_ECD6AF4391D10E6 ON md_news_letter_group_user;
ALTER TABLE md_news_letter_group_user CHANGE md_newsletter_group_id md_newsletter_group_id INT NOT NULL, CHANGE md_newsletter_user_id md_newsletter_user_id INT NOT NULL;
ALTER TABLE md_blocked_users CHANGE md_user_id md_user_id INT NOT NULL;
ALTER TABLE md_galeria_translation DROP FOREIGN KEY md_galeria_translation_id_md_galeria_id;
--DROP INDEX IDX_82B8EFDDBF396750 ON md_galeria_translation;
ALTER TABLE md_galeria_translation CHANGE id id INT NOT NULL, CHANGE lang lang VARCHAR(2) NOT NULL;
ALTER TABLE md_content_relation DROP FOREIGN KEY md_content_relation_md_content_id_first_md_content_id;
ALTER TABLE md_content_relation DROP FOREIGN KEY md_content_relation_md_content_id_second_md_content_id;
--DROP INDEX IDX_3ADCF59524A11DBB ON md_content_relation;
ALTER TABLE md_content_relation CHANGE md_content_id_first md_content_id_first INT NOT NULL, CHANGE md_content_id_second md_content_id_second INT NOT NULL;
ALTER TABLE md_content DROP FOREIGN KEY md_content_md_user_id_md_user_id;
--ALTER TABLE md_news_letter_group_sended DROP FOREIGN KEY mmmi;
--ALTER TABLE md_news_letter_group_sended DROP FOREIGN KEY mmmi_1;
--DROP INDEX IDX_38685392391D10E6 ON md_news_letter_group_sended;
ALTER TABLE md_news_letter_group_sended CHANGE md_newsletter_group_id md_newsletter_group_id INT NOT NULL, CHANGE md_newsletter_contend_sended_id md_newsletter_contend_sended_id INT NOT NULL;
ALTER TABLE md_media_album DROP FOREIGN KEY md_media_album_md_media_content_id_md_media_content_id;
ALTER TABLE md_media_album DROP FOREIGN KEY md_media_album_md_media_id_md_media_id;
ALTER TABLE md_media_album CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE counter_content counter_content BIGINT DEFAULT NULL;
ALTER TABLE emails CHANGE id id INT NOT NULL;
ALTER TABLE md_newsletter_send DROP FOREIGN KEY md_newsletter_send_md_news_letter_user_id_md_news_letter_user_id;
ALTER TABLE md_newsletter_send DROP FOREIGN KEY mmmi_5;
ALTER TABLE usuario CHANGE egresado egresado TINYINT(1) DEFAULT NULL;
ALTER TABLE usuario_actividades DROP FOREIGN KEY usuario_actividades_actividad_id_actividades_id;
ALTER TABLE usuario_actividades DROP FOREIGN KEY usuario_actividades_usuario_id_usuario_id;
ALTER TABLE usuario_actividades CHANGE usuario_id usuario_id INT NOT NULL, CHANGE actividad_id actividad_id INT NOT NULL;
ALTER TABLE usuario_actividades ADD CONSTRAINT FK_4BFEBA50DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id);
ALTER TABLE usuario_actividades ADD CONSTRAINT FK_4BFEBA506014FACA FOREIGN KEY (actividad_id) REFERENCES actividades (id);
ALTER TABLE cuentausuario DROP FOREIGN KEY cuentausuario_cuenta_id_cuenta_id;
ALTER TABLE cuentausuario DROP FOREIGN KEY cuentausuario_usuario_id_usuario_id;
ALTER TABLE cuentausuario DROP PRIMARY KEY;
ALTER TABLE cuentausuario CHANGE cuenta_id cuenta_id INT NOT NULL, CHANGE usuario_id usuario_id INT NOT NULL;
ALTER TABLE cuentausuario ADD CONSTRAINT FK_E00E5590DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id);
ALTER TABLE cuentausuario ADD CONSTRAINT FK_E00E55909AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id);
ALTER TABLE cuentausuario ADD PRIMARY KEY (usuario_id, cuenta_id);
ALTER TABLE hermanos DROP FOREIGN KEY hermanos_usuario_from_usuario_id;
ALTER TABLE hermanos DROP FOREIGN KEY hermanos_usuario_to_usuario_id;
ALTER TABLE hermanos CHANGE usuario_from usuario_from INT NOT NULL, CHANGE usuario_to usuario_to INT NOT NULL;
ALTER TABLE hermanos ADD CONSTRAINT FK_725039B1D060DB60 FOREIGN KEY (usuario_from) REFERENCES usuario (id);
ALTER TABLE hermanos ADD CONSTRAINT FK_725039B1B386F60A FOREIGN KEY (usuario_to) REFERENCES usuario (id);
ALTER TABLE cobro DROP FOREIGN KEY cobro_cuenta_id_cuenta_id;
ALTER TABLE cobro CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE monto monto DOUBLE PRECISION NOT NULL;
ALTER TABLE cobro ADD CONSTRAINT FK_F0A265269AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id);
ALTER TABLE md_user_search DROP FOREIGN KEY md_user_search_md_user_id_md_user_id;
ALTER TABLE md_user_search CHANGE active active TINYINT(1) DEFAULT NULL, CHANGE blocked blocked TINYINT(1) DEFAULT NULL, CHANGE admin admin TINYINT(1) DEFAULT NULL, CHANGE show_email show_email TINYINT(1) DEFAULT NULL;
ALTER TABLE facturaFinal DROP FOREIGN KEY facturaFinal_cuenta_id_cuenta_id;
ALTER TABLE facturaFinal CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE total total DOUBLE PRECISION NOT NULL, CHANGE pago pago TINYINT(1) NOT NULL, CHANGE cancelado cancelado TINYINT(1) NOT NULL, CHANGE enviado enviado TINYINT(1) NOT NULL, CHANGE pagadodeltotal pagadodeltotal DOUBLE PRECISION NOT NULL;
ALTER TABLE facturaFinal ADD CONSTRAINT FK_DA66D039AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id);
ALTER TABLE facturaUsuarioDetalle DROP FOREIGN KEY facturaUsuarioDetalle_factura_id_facturaUsuario_id;
ALTER TABLE facturaUsuarioDetalle CHANGE factura_id factura_id BIGINT DEFAULT NULL, CHANGE amount amount DOUBLE PRECISION NOT NULL;
ALTER TABLE facturaUsuarioDetalle ADD CONSTRAINT FK_F70A5653F04F795F FOREIGN KEY (factura_id) REFERENCES facturaUsuario (id);
ALTER TABLE facturaUsuario DROP FOREIGN KEY facturaUsuario_usuario_id_usuario_id;
ALTER TABLE facturaUsuario CHANGE usuario_id usuario_id INT DEFAULT NULL, CHANGE total total DOUBLE PRECISION NOT NULL, CHANGE enviado enviado TINYINT(1) NOT NULL, CHANGE pago pago TINYINT(1) NOT NULL, CHANGE cancelado cancelado TINYINT(1) NOT NULL;
ALTER TABLE facturaUsuario ADD CONSTRAINT FK_C536721FDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id);
ALTER TABLE facturausuariofinal DROP FOREIGN KEY facturausuariofinal_factura_final_id_facturaFinal_id;
ALTER TABLE facturausuariofinal DROP FOREIGN KEY facturausuariofinal_factura_usuario_id_facturaUsuario_id;
DROP INDEX facturausuariofinal_factura_final_id_facturaFinal_id ON facturausuariofinal;
--DROP INDEX IDX_41095553322197E5 ON facturausuariofinal;
ALTER TABLE facturausuariofinal DROP PRIMARY KEY;
ALTER TABLE facturausuariofinal ADD facturausuario_id BIGINT NOT NULL, ADD facturafinal_id BIGINT NOT NULL, DROP factura_usuario_id, DROP factura_final_id;
ALTER TABLE facturausuariofinal ADD CONSTRAINT FK_41095553ECD5AC85 FOREIGN KEY (facturausuario_id) REFERENCES facturaUsuario (id) ON DELETE CASCADE;
ALTER TABLE facturausuariofinal ADD CONSTRAINT FK_4109555372970A05 FOREIGN KEY (facturafinal_id) REFERENCES facturaFinal (id) ON DELETE CASCADE;
CREATE INDEX IDX_41095553ECD5AC85 ON facturausuariofinal (facturausuario_id);
CREATE INDEX IDX_4109555372970A05 ON facturausuariofinal (facturafinal_id);
ALTER TABLE facturausuariofinal ADD PRIMARY KEY (facturausuario_id, facturafinal_id);
ALTER TABLE md_news_letter_user DROP FOREIGN KEY md_news_letter_user_md_user_id_md_user_id;
ALTER TABLE cuenta CHANGE debe debe DOUBLE PRECISION DEFAULT NULL, CHANGE pago pago DOUBLE PRECISION DEFAULT NULL, CHANGE diferencia diferencia DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE md_newsletter_content_sended DROP FOREIGN KEY mmmi_4;
ALTER TABLE md_newsletter_content_sended CHANGE sended sended TINYINT(1) DEFAULT NULL, CHANGE for_status for_status SMALLINT DEFAULT NULL;
ALTER TABLE pagos DROP FOREIGN KEY pagos_usuario_id_usuario_id;
ALTER TABLE pagos CHANGE usuario_id usuario_id INT DEFAULT NULL, CHANGE out_of_date out_of_date TINYINT(1) NOT NULL;
ALTER TABLE pagos ADD CONSTRAINT FK_DA9B0DFFDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id);

