<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CobrosRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CobrosRepository extends EntityRepository
{
    public function retrieveLastFromAccount($accountId)
    {
        $dql = 'select c from AppBundle:Cobro c where c.cuenta = :cuenta order by c.fecha desc';

        return $this->getEntityManager()->createQuery($dql)->setParameters(array(
        'cuenta' => $accountId,
    ))->setMaxResults(1)->getOneOrNullResult();
    }
}
