<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CostosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostosRepository extends EntityRepository
{
  public function getCostoValue(){
    $dql = 'select c from AppBundle:Costos c';
    return $this->getEntityManager()->createQuery($dql)->setMaxResults(1)->getOneOrNullResult();
  }
}
