<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaRepository extends EntityRepository
{
  
  public function retrieveAllPendingDebts()
  {
    $sql = 'select c.id as cuentaId, c.diferencia, c.referenciabancaria, e.id as estudianteId, e.nombre, e.apellido, e.horario, e.clase from cuenta c inner join estudiante_cuenta ec on c.id = ec.cuenta_id inner join estudiante e on e.id = ec.estudiante_id where c.diferencia > 0';
    $data = $this->getEntityManager()->getConnection()->executeQuery($sql);//->fetchAll();
    $returnList = array();
    while($row = $data->fetch())
    {
      if(isset($returnList[$row['cuentaId']]))
      {
          $returnList[$row['cuentaId']] = array();
      }
      $returnList[$row['cuentaId']][] = $row;
    }
    return $returnList;
  }
}
