<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaEstudianteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaEstudianteRepository extends EntityRepository
{
    public function retrieveFacturaOfEstudiantePerMonthAndYear($estudiante, $month, $year)
    {
        $dql = 'select f from AppBundle:FacturaEstudiante f where f.estudiante = :estudiante and f.month = :month and f.year = :year';

        return $this->getEntityManager()->createQuery($dql)->setParameters(array(
        'estudiante' => $estudiante,
        'month' => $month,
        'year' => $year,
    ))->setMaxResults(1)->getOneOrNullResult();
    }

    public function retrieveFacturaOfEstudiantePerAccountMonthAndYear($cuenta, $month, $year)
    {
        $dql = 'select f from AppBundle:FacturaEstudiante f join f.estudiante e where e.cuenta = :cuenta and f.month = :month and f.year = :year';

        return $this->getEntityManager()->createQuery($dql)->setParameters(array(
        'cuenta' => $cuenta,
        'month' => $month,
        'year' => $year,
    ))->getResult();
    }
}
