<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaFinalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaFinalRepository extends EntityRepository
{
  
    public function retrieveFacturaFinalOfAccountPerMonthAndYear($account, $month, $year)
    {
      $dql = 'select f from AppBundle:FacturaFinal f where f.cuenta = :cuenta and f.month = :month and f.year = :year';
      return $this->getEntityManager()->createQuery($dql)->setParameters(array(
          'cuenta' => $account,
          'month' => $month,
          'year' => $year
      ))->setMaxResults(1)->getOneOrNullResult();
    }
}
