<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * FacturaEstudianteDetalle.
 *
 * @ORM\Table(name="factura_estudiante_detalle", indexes={@ORM\Index(name="factura_id_idx", columns={"factura_id"})})
 * @ORM\Entity
 */
class FacturaEstudianteDetalle
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="bigint")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="FacturaEstudiante", inversedBy="facturaDetalles")
     * @ORM\JoinColumn(name="factura_id", referencedColumnName="id", nullable=false)
     **/
    private $factura;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @var float
     *
     * @ORM\Column(name="amount", type="float", precision=12, scale=2, nullable=false, options={"default": 0})
     */
    private $amount;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime", nullable=false)
     */
    private $updatedAt;

    /**
     * @ORM\Column(name="autogenerated", type="boolean", nullable=false, options={"default": 1})
     **/
    private $autogenerated;

    /**
     * Set id.
     *
     * @return int
     */
    public function setId($id)
    {
        $this->id = $id;

        return  $this;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set description.
     *
     * @param string $description
     *
     * @return FacturaEstudianteDetalle
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set amount.
     *
     * @param float $amount
     *
     * @return FacturaEstudianteDetalle
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * Get amount.
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Set createdAt.
     *
     * @param \DateTime $createdAt
     *
     * @return FacturaEstudianteDetalle
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt.
     *
     * @param \DateTime $updatedAt
     *
     * @return FacturaEstudianteDetalle
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set factura.
     *
     * @param \AppBundle\Entity\FacturaEstudiante $factura
     *
     * @return FacturaEstudianteDetalle
     */
    public function setFactura(\AppBundle\Entity\FacturaEstudiante $factura = null)
    {
        $this->factura = $factura;

        return $this;
    }

    /**
     * Get factura.
     *
     * @return \AppBundle\Entity\FacturaEstudiante
     */
    public function getFactura()
    {
        return $this->factura;
    }

    public function generateUniqueHash()
    {
        return md5($this->getFactura()->getId().$this->getAmount().$this->getDescription());
    }

    /**
     * Set autogenerated.
     *
     * @param bool $autogenerated
     *
     * @return FacturaEstudianteDetalle
     */
    public function setAutogenerated($autogenerated)
    {
        $this->autogenerated = $autogenerated;

        return $this;
    }

    /**
     * Get autogenerated.
     *
     * @return bool
     */
    public function getAutogenerated()
    {
        return $this->autogenerated;
    }
}
