<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstudianteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgenitorRepository extends EntityRepository
{
    public function getActiveForList($page = 0, $limit = 10, $orderBy = 'nombre', $order = 'ASC')
    {
        $dql = sprintf('SELECT p.id, p.nombre, p.email, p.direccion, p.telefono, p.celular FROM AppBundle:Progenitor p ORDER BY p.%s %s', $orderBy, $order);

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setMaxResults($limit)
            ->setFirstResult(($page * $limit))
            ->getResult();
    }
}
