listado_cuentas:
    path:     /listado.html
    defaults: { _controller: AppBundle:Cuentas:list }

show_cuenta:
    path:     /{id}/cuenta
    defaults: { _controller: AppBundle:Cuentas:show }

disable_factura:
    path:     /{id}/disable-factura
    defaults: { _controller: "AppBundle:Cuentas:disableFactura" }
    methods:  [POST, PUT]

enable_factura:
    path:     /{id}/enable-factura
    defaults: { _controller: "AppBundle:Cuentas:enableFactura" }
    methods:  [POST, PUT]

add_detalle_factura:
    path:     /{facturaId}/add-factura
    defaults: { _controller: "AppBundle:Cuentas:addDetalleFacturaForm" }

save_detalle_factura:
    path:     /{facturaId}/save-factura
    defaults: { _controller: "AppBundle:Cuentas:saveDetalleFacturaForm" }
    methods:  [POST, PUT]

reset_detalle_factura:
    path:     /{facturaId}/reset-factura
    defaults: { _controller: "AppBundle:Cuentas:resetDetalleFacturaForm" }

save_reset_factura:
    path:     /{facturaId}/save-reset-factura
    defaults: { _controller: "AppBundle:Cuentas:saveResetDetalleFacturaForm" }
    methods:  [POST, PUT]

send_emails_cuenta:
    path:     /{id}/send-email
    defaults: { _controller: "AppBundle:Cuentas:sendEmailToCuenta" }