listado_cuentas:
    path:     /listado.html
    defaults: { _controller: AppBundle:Cuentas:list }

show_cuenta:
    path:     /{id}/cuenta
    defaults: { _controller: AppBundle:Cuentas:show }

view_cobro_pdf:
    path:     /{id}/pdf-cobro
    defaults: { _controller: "AppBundle:Cuentas:showCobroPdf" }

add_cobro:
    path:     /{cuentaId}/add-cobro
    defaults: { _controller: "AppBundle:Cuentas:addCobroForm" }

save_cobro:
    path:     /{cuentaId}/save-cobro
    defaults: { _controller: "AppBundle:Cuentas:saveCobroForm" }
    methods:  [POST, PUT]

disable_cobro:
    path:     /{id}/disable-cobro
    defaults: { _controller: "AppBundle:Cuentas:disableCobro" }
    methods:  [POST, PUT]

enable_cobro:
    path:     /{id}/enable-cobro
    defaults: { _controller: "AppBundle:Cuentas:enableCobro" }
    methods:  [POST, PUT]
