listado_cuentas:
    path:     /listado.html
    defaults: { _controller: AppBundle:Cuentas:list }

show_cuenta:
    path:     /{id}/cuenta
    defaults: { _controller: AppBundle:Cuentas:show }

view_cobro_pdf:
    path:     /{id}/pdf-cobro
    defaults: { _controller: "AppBundle:Cuentas:showCobroPdf" }
