estudiante:
    path:     /list/{page}/{orderBy}/{order}/{limit}
    defaults: { _controller: "AppBundle:Estudiante:index", page: 0, orderBy: 'apellido', order : 'asc', limit: 20 }

estudiante_search:
    path:     /search
    defaults: { _controller: "AppBundle:Estudiante:search" }

estudiante_futuros:
    path:     /futuros/list/{page}/{orderBy}/{order}/{limit}
    defaults: { _controller: "AppBundle:Estudiante:futuros", page: 0, orderBy: 'apellido', order : 'asc', limit: 20 }

estudiante_futuros_search:
    path:     /futuros/search
    defaults: { _controller: "AppBundle:Estudiante:futurosSearch" }

estudiante_egresados:
    path:     /egresados/list/{page}/{orderBy}/{order}/{limit}
    defaults: { _controller: "AppBundle:Estudiante:egresados", page: 0, orderBy: 'apellido', order : 'asc', limit: 20 }

estudiante_egresados_search:
    path:     /egresados/search
    defaults: { _controller: "AppBundle:Estudiante:egresadosSearch" }

estudiante_check_reference:
    path:     /check-reference
    defaults: { _controller: "AppBundle:Estudiante:checkReference" }
    methods:  [POST, PUT]

estudiante_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Estudiante:show" }

estudiante_new:
    path:     /new
    defaults: { _controller: "AppBundle:Estudiante:new" }

estudiante_create:
    path:     /create
    defaults: { _controller: "AppBundle:Estudiante:create" }
    methods:  POST

estudiante_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Estudiante:edit" }

estudiante_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Estudiante:update" }
    methods:  [POST, PUT]

estudiante_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Estudiante:delete" }
    methods:  [POST, DELETE]

estudiante_pdf_cuenta:
    path:     /{id}/pdf-cuenta
    defaults: { _controller: "AppBundle:Estudiante:showAccountPdf" }
