rnewsletter_index:
    path:     /r/index
    defaults: { _controller: AppBundle:ReactNewsletter:index }

rnewsletter_user_count_url:
    path:     /r/get-user-counter
    defaults: { _controller: AppBundle:ReactNewsletter:userCounter }

rnewsletter_user_add_url:
    path:     /r/add-user
    defaults: { _controller: AppBundle:ReactNewsletter:userAdd }

rnewsletter_search_users:
    path:     /r/search-list-users
    defaults: { _controller: AppBundle:ReactNewsletter:searchListUsers }
    requirements: { _method: post }

rnewsletter_remove_users:
    path:     /r/remove-list-user
    defaults: { _controller: AppBundle:ReactNewsletter:removeListUser }
    requirements: { _method: post }
